---
title: "CovFit"
author: "TS"
date: "3 Juli 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Growth curve analysis and plotting with R
2017: http://rstudio-pubs-static.s3.amazonaws.com/270755_b6a3cb371b0b446891deba7aa7fa55f2.html

### Package: Growthcurver
Fits logistic curve to growth data obtained from a plate reader

# Fitting Non-Linear Growth Curves in R
2017: http://www.statsathome.com/2017/06/07/fitting-non-linear-groth-curves-in-r/

### Package: nls

### Gompert Function
Sigmoid function with parameters for height(a), shift(b) and growth rate(c)
Special case of the 'Generalized Logistic function'
formula.gompertz <- "y~a*exp(-exp(mu*exp(1)/a*(lambda-t)+1))"
f(t) = a*exp(-b*exp(-ct))


# Estimation of Growth Rates with Package growthrates
2019: https://cran.r-project.org/web/packages/growthrates/vignettes/Introduction.html

### Package: growthrates
https://tpetzoldt.github.io/growthrates/doc/Introduction.html


# COVID-19 in Belgium
2020: https://www.statsandr.com/blog/covid-19-in-belgium/
https://www.statsandr.com/blog/top-r-resources-on-covid-19-coronavirus/

### Packages: deSolve, optim

### SIR function in R

```{}
SIR <- function(time, state, parameters) {
  par <- as.list(c(state, parameters))
  with(par, {
    dS <- -beta * I * S / N
    dI <- beta * I * S / N - gamma * I
    dR <- gamma * I
    list(c(dS, dI, dR))
  })
}
```

### Fitting a SIR model to the Belgium data

To fit the model to the data we need two things:
-     a solver for these differential equations
-     an optimiser to find the optimal values for our two unknown parameters, β and γ

Specifically, what we need to do is minimise the sum of the squared differences between I(t), which is the number of people in the infectious compartment I at time t, and the corresponding number of cases as predicted by our model ^I(t). This quantity is known as the residual sum of squares (RSS):

RSS(β,γ)=∑t(I(t)−^I(t))2


```{}
# define a function to calculate the residual sum of squares
# (RSS), passing in parameters beta and gamma that are to be
# optimised for the best fit to the incidence data
RSS <- function(parameters) {
  names(parameters) <- c("beta", "gamma")
  out <- ode(y = init, times = Day, func = SIR, parms = parameters)
  fit <- out[, 3]
  sum((Infected - fit)^2)
}
```
Finally, we can fit the SIR model to our data by finding the values for β and γ that minimise the residual sum of squares between the observed cumulative incidence (observed in Belgium) and the predicted cumulative incidence (predicted by our model). We also need to check that our model has converged, as indicated by the message shown below:

```{}
# now find the values of beta and gamma that give the
# smallest RSS, which represents the best fit to the data.
# Start with values of 0.5 for each, and constrain them to
# the interval 0 to 1.0

# install.packages("deSolve")
library(deSolve)

Opt <- optim(c(0.5, 0.5),
  RSS,
  method = "L-BFGS-B",
  lower = c(0, 0),
  upper = c(1, 1)
)

# check for convergence
Opt$message

Opt_par <- setNames(Opt$par, c("beta", "gamma"))

# get the fitted values from our SIR model
fitted_cumulative_incidence <- data.frame(ode(
  y = init, times = t,
  func = SIR, parms = Opt_par
))

R0 <- as.numeric(Opt_par[1] / Opt_par[2])

```

### Package: incidence
R Epidemics Consortium (RECON)
https://www.repidemicsconsortium.org/incidence/

### Package: EpiEstim
https://www.sciencedirect.com/science/article/pii/S1755436519300350
https://cran.r-project.org/web/packages/EpiEstim/vignettes/demo.html
Model with non-constant R0
- Calculates R0 from incident data and serial interval (time from symptoms of infected to symtoms in transmitted)
- SI can be formulated as parameters of distribution
- R0 is calculated from a sliding window (default 1 week)
- R0 can be estimated for date intervals to estimate R0 for lock down measures



### Package: projections
More complex models than SIR




